### PR TITLE
Update to 1.20.6

### PR DESCRIPTION
**Pull request by GrinlexGH**

### CODE REVIEW

**Comment by GrinlexGH** [comment]
Oh no, I found a bug, when exp bar will not render. Im working on it

**Comment by GrinlexGH** [comment]
fixed

**Comment by GrinlexGH** [comment]
oh no, another bug when xp level won't render when player press jump key

**Comment by GrinlexGH** [comment]
fixed

**Comment by Lortseam** [comment]
Thanks so much! I will have a look at this when I have time.

**Comment by Tapacywka** [comment]
> fixed

Perhaps you can look at it right away?
https://github.com/Lortseam/better-mount-hud/issues/11

**Comment by GrinlexGH** [comment]
> > fixed
> 
> Perhaps you can look at it right away? #11

this was a problem of minecraft itself, which was fixed once. it seems to be at 1.20.5, but I'm not sure. In any case, this bug was not present in my tests on 1.20.6

**Pull request merged**
